### ISSUE TITLE
Reproducibility problem. Missing file or folder?

### ISSUE THREAD

**Issue by LFMP** [PlusLabNLP/Plot-guided-Coherence-Evaluation#4]
Hello,
I'm trying to generate the negative samples using the available checkpoint, but some file or folder seems to be missing, specifically `wp_kw_story-bin` and `rocstories_kw_story-bin`.

Could you make these files available, or the script for training the BART model? The script would be especially useful for other researchers, including myself, to test with other databases as well.

Below I show the error I am getting when trying to use the make_AF_input_WP.py and make_AF_input_ROC.py files.

```
2023-06-01 00:20:14 | INFO | fairseq.file_utils | loading archive file Models/Ft_BART_Story_Generator/WP/
2023-06-01 00:20:14 | INFO | fairseq.file_utils | Archive name 'wp_kw_story-bin' was not found in archive name list. We assumed 'wp_kw_story-bin' was a path or URL but couldn't find any file associated to this path or URL.
Traceback (most recent call last):
  File "make_AF_input_WP.py", line 115, in <module>
    af = AF_Data_Generation(args.bart_model_path)
  File "make_AF_input_WP.py", line 16, in __init__
    data_name_or_path='wp_kw_story-bin'
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by SarikGhazarian** [comment]
Hello,

I followed steps in fairseq to train BART. For your convenience I have added those folders to the Github repo.
